### ISSUE TITLE
Fix Arm dto to match Drive dto format

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-control-systems-2022#210]
Current DTOs are as follow
``` 
drive command dto 
{"HB":0,"IO":1,"WO":0,"DM":"D","CMD":[0,0]}

arm command dto 
{"heartbeat_count":0,"is_operational":1,"mode":"J","angles":[0,0,0,0,0]} 
```
Make arm be same format e.g. `{"HB":0,"IO":1,"M":"J","CMD":[0,0,0,0,0]}`
I also think drive should be `{"HB":0,"IO":1,"WO":0,"M":"D","CMD":[0,0]}` for consistency

**Comment by kammce** [comment]
If you want to stick with JSON you should definitely stick to the human readable format of the DTO. The original purposes of JSON was to be a human readable data format. 

I believe this shortening was due to a need to reduce the number of bytes parsed by the server in order to improve performance, but moving from 43 bytes to 73 bytes shouldn't make a difference. Or in other words, solve the root issue and refrain from adding bandages.
